package se.statenspersonadressregister.referensimplementation.loggning;

public class PersonsokExempelLogTexter {
    public static final char RADBRYT = '\n';
    public static final String PERSON_ID = "  PersonId = ";
    public static final String DATUM_FROM = "    Datum from = ";
    public static final String DATUM_TILL = "    Datum till = ";
    public static final String AVLIDENDATUM = "    Avlidendatum = ";
    public static final String AVREGISTRERINGSORSAK_KOD = "    Avregistreringsorsakkod = ";
    public static final String ANTRAFFAD_DOD = "    Anträffad död = ";
    public static final String FORNAMN = "    Förnamn = ";
    public static final String MELLANNAMN = "    Mellannamn = ";
    public static final String EFTERNAMN = "    Efternamn = ";
    public static final String AVISERINGSNAMN = "    Aviseringsnamn = ";
    public static final String TILLTALSNAMN = "    Tilltalsnamn = ";
    public static final String FODELSELAN_KOD = "    FödelselanKod = ";
    public static final String FODELSEFORSAMLING = "    Födelseforsamling = ";
    public static final String FODELSETID = "    Födelsetid = ";
    public static final String HANVISNINGS_PERSON_NR_BYTT_FRAN = "    Hänvisningspersonnr bytt från = ";
    public static final String HANVISNINGS_PERSON_NR_BYTT_TILL = "    Hänvisningspersonnr bytt till = ";
    public static final String SEKRETESSMARKERING1 = "  Sekretessmarkering = ";
    public static final String SEKRETESSMARKERING2 = "    Sekretessmarkering = ";
    public static final String SEKRETESS_SATT_AV_SPAR1 = "  Sekretess satt av SPAR = ";
    public static final String SEKRETESS_SATT_AV_SPAR2 = "    Sekretess satt av SPAR = ";
    public static final String SKYDDAD_FOLKBOKFORING1 = "  Skyddad folkbokföring = ";
    public static final String SKYDDAD_FOLKBOKFORING2 = "    Skyddad folkbokföring = ";
    public static final String KON = "    Kön = ";
    public static final String SVENSK_MEDBORGARE = "    Svensk medborgare = ";
    public static final String KOD = "  Kod = ";
    public static final String BESKRIVNING = "  Beskrivning = ";
    public static final String AVISERINGSPOST = "Aviseringspost";
    public static final String PERSONDETALJ = "  Persondetalj";
    public static final String MELLANSLAG = " ";
    public static final String SOKTRAFFAR = " sökträffar, ";
    public static final String ANTAL_UNDANTAG = " undantag";
    public static final String OVERSTIGER_MAX_ANTAL_TRAFFAR = "  Överstiger maximalt antal träffar, ";
    public static final String TRAFFAR_AV_MAX = " träffar av maximalt ";
    public static final String SPARPERSONSOKNING_SVAR = "SPARPersonsokningSvar:";
    public static final String UNDANTAG = "Undantag";
    public static final String INKOMST_AR = "  Inkomstår = ";
    public static final String SUMMERAD_INKOMST = "  Summerad inkomst = ";
    public static final String SEKRETESS_ANDRINGSDATUM = "  Sekretessändringsdatum = ";
    public static final String SKYDDAD_FOLKBOKFORING_ANDRINGSDATUM = "  Skyddad folkbokföring ändringsdatum = ";
    public static final String SENASTE_ANDRING_SPAR = "  SenasteAndringSPAR = ";
    public static final String RELATIONSTYP = "  Relationstyp = ";
    public static final String RELATION = "Relation";
    public static final String CARE_OF = "    Care of = ";
    public static final String UTDELNINGSADRESS_1 = "    Utdelningsadress 1 = ";
    public static final String UTDELNINGSADRESS_2 = "    Utdelningsadress 2 = ";
    public static final String UTDELNINGSADRESS_3 = "    Utdelningsadress 3 = ";
    public static final String POSTORT = "    Postort = ";
    public static final String POSTNUMMER = "    Postnummer = ";
    public static final String FOLKBOKFORINGSADRESS = "  Folkbokföringsadress";
    public static final String FOLKBOKFORDSFORSAMLINGKOD = "    Folkbokfordsförsamlingkod = ";
    public static final String DISTRIKTKOD = "    Distriktkod = ";
    public static final String KOMMUNKOD = "    Kommunkod = ";
    public static final String LANKOD = "    Länkod = ";
    public static final String UTLANDSADRESS = "  Utlandsadress";
    public static final String SARSKILD_POSTADRESS = "  Särskild postadress";
    public static final String LAND = "    Land = ";
    public static final String FASTIGHET = "  Fastighet";
    public static final String FASTIGHETSKOD = "    Fastighetskod = ";
    public static final String TAXERINGSENHETSNUMMER = "    Taxeringsenhetsnummer = ";
    public static final String KOMMUN = "    Kommun = ";
    public static final String LAN = "    Län = ";
    public static final String TAXERINGSAR = "    Taxeringsår = ";
    public static final String TAXERINGSVARDE = "    Taxeringsvärde = ";
    public static final String FASTIGHETDEL = "    Fastighetdel";
    public static final String ANDELSTAL_TALJARE = "      Andelstal täljare = ";
    public static final String ANDELSTAL_NAMNARE = "      Andelstal nämnare = ";
    public static final String FASTIGHET_BETECKNING = "      Fastighet beteckning = ";
    public static final String TAXERINGSIDENTITET = "      Taxeringsidentitet = ";

}
